In [1]:
from absenteeism_module import *
model = absenteeism_model('model', 'scaler')
model.load_and_clean_data('Absenteeism_data.csv')
model.predicted_outputs()

,Reason_1,Reason_2,Reason_3,Reason_4,Month Value,Transportation Expense,Age,Body Mass Index,Education,Children,Pets,Probability,Prediction
0,False,False,False,True,7,289,33,30,0,2,1,0.590827,1
1,False,False,False,False,7,118,50,31,0,1,0,0.076181,0
2,False,False,False,True,7,179,38,31,0,0,0,0.250934,0
3,True,False,False,False,7,279,39,24,0,2,0,0.872203,1
4,False,False,False,True,7,289,33,30,0,2,1,0.590827,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
695,True,False,False,False,5,179,40,22,1,2,0,0.633687,1
696,True,False,False,False,5,225,28,24,0,1,2,0.698584,1
697,True,False,False,False,5,330,28,25,1,0,0,0.860255,1
698,False,False,False,True,5,235,32,25,1,0,0,0.246310,0
699,False,False,False,True,5,291,40,25,0,1,1,0.369477,0

In [2]:
import pymysql

conn = pymysql.connect(database = 'predicted_outputs', user = 'root', password = '120398')

OperationalError: (1049, "Unknown database 'predicted_outputs'")

In [ ]:
cursor = conn.cursor()

# # Checkpoint 'df_new_obs'

In [ ]:
df_new_obs = model.predicted_outputs()
df_new_obs

NameError: name 'model' is not defined

## .execute()

In [ ]:
cursor.execute('SELECT * FROM predicted_outputs;') # 0 means the data table is empty.

0

## Creating the INSERT Statement

In [ ]:
insert_query = 'INSERT INTO predicted_outputs VALUES '

In [ ]:
df_new_obs.shape

(40, 13)

In [ ]:
df_new_obs['Age']

0     30
1     28
2     34
3     40
4     34
5     28
6     46
7     30
8     37
9     37
10    36
11    50
12    31
13    30
14    48
15    33
16    50
17    30
18    40
19    30
20    37
21    31
22    37
23    37
24    31
25    43
26    31
27    58
28    37
29    58
30    33
31    37
32    28
33    28
34    31
35    33
36    37
37    40
38    39
39    53
Name: Age, dtype: int64

In [ ]:
df_new_obs[df_new_obs.columns.values[6]][0]

30

In [ ]:
for i in range(df_new_obs.shape[0]):
    insert_query += '(' 
    
    for j in range(df_new_obs.shape[1]):
        insert_query += str(df_new_obs[df_new_obs.columns.values[j]][i]) + ', '
    
    insert_query = insert_query[:-2] + '), '

In [ ]:
insert_query = insert_query[:-2] + ';' # Completing the query
print(insert_query)

In [ ]:
cursor.execute(insert_query)

40

In [ ]:
conn.commit() # Committing the changes

In [ ]:
conn.close() # Closing the connection